/**
 * Build the DSH browser bundle from the feature source files.
 *
 * Usage:
 *   node scripts/build.mjs
 *
 * The generated file is `lib/client.js`. DSH serves only this one file, so the
 * browser side must be bundled even though the source is split by feature.
 */
import { readFile, writeFile } from "node:fs/promises";

const parts = [
	"lib/session-color.js",
	"lib/workspace-tree.js",
	"lib/layout-ui.js",
	"lib/sound-alert.js",
	"lib/entry.js"
];

const banner = [
	"/**",
	" * dsh_ux_enhance — browser half (generated bundle).",
	" * Generated by scripts/build.mjs from:",
	" *   - lib/session-color.js",
	" *   - lib/layout-ui.js",
	" *   - lib/sound-alert.js",
	" *   - lib/entry.js",
	" * Do not edit directly.",
	" */"
].join("\n");

const contents = await Promise.all(parts.map((file) => readFile(new URL(`../${file}`, import.meta.url), "utf8")));
const output = banner + "\n" + contents.join("\n\n") + "\n";
await writeFile(new URL("../lib/client.js", import.meta.url), output, "utf8");
console.log("built lib/client.js");
